### ISSUE TITLE
Doesn't work in latest beta release 1.5.10.

### ISSUE THREAD

**Issue by DudeThatsErin** [NemoAndrea/obsidian-daily-folder#4]
I have my notes located in 2 places (cause I am merging 2 vaults into 1) and when I attempt to move them from the 2 places into the "daily-notes" folder that was created when I use this, the notes stay for a bit and then get deleted by the plugin.

![image](https://github.com/NemoAndrea/obsidian-daily-named-folder/assets/2681022/7d0bf091-7cc9-492d-9d2c-3b21c353e123)

Saying the files can't be found cause they are deleted. I watch this happen in my Windows 10 file explorer as well as inside Obsidian and the Dev console.

This is my debug info with the plugin uninstalled (cause it doesn't work).

```
SYSTEM INFO:
	Obsidian version: v1.5.10
	Installer version: v1.5.8
	Operating system: Windows 10 Home 10.0.22631
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 8
	Plugins enabled: 6
		1: Banners v2.0.5-beta
		2: Calendar v1.5.10
		3: Iconize v2.10.1
		4: Projects v1.17.1
		5: Emoji Shortcodes v2.2.0
		6: DataLoom v8.15.12

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by NemoAndrea** [comment]
Hmm I have not experienced these issues and it is working on V1.6.7

I am not sure if the plugin itself could be deleting files; I dont think I have added any functionality that should touch it; so maybe some other process or plugin on your system was doing that?

Otherwise I am not sure how to go about avoiding this. Feel free to reopen if you think it was the plugin and have suggestions on where to start.
